# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [-b, master]
  - repo: local
    hooks:
      - id: mix-format
        name: "elixir: mix format"
        entry: mix format
        language: system
        files: \.exs?$

      - id: mix-compile
        name: "elixir: mix compile"
        entry: mix compile
        language: system
        pass_filenames: false
        files: \.ex$

      - id: mix-test
        name: "elixir: mix test"
        entry: mix test
        language: system
        pass_filenames: false
        files: \.exs?$

      - id: mix-credo
        name: "elixir: mix credo"
        entry: mix credo --all
        language: system
        pass_filenames: false
        files: \.exs*$

      - id: mix-dialyzer
        name: "elixir: mix dialyzer"
        entry: mix dialyzer --force-check --format short
        language: system
        pass_filenames: false
        files: \.exs?$

